[package]
name = "smbuilder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "smbuilder"
path = "crates/smbuilder/lib.rs"
test = true
crate-type = ["lib"]

[dependencies]
